In [3]:
import sys
sys.path.append("..")
%load_ext autoreload
%autoreload 2

In [20]:
from IPython.display import Markdown, display

## Testing connection to gemini API

In [1]:
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    project="saferfood-488120",
    location="northamerica-northeast1",
)

print(llm.invoke("Say hello").content)

Hello!

## Testing explanations module

In [4]:
from interface import explanations

In [28]:
exp = explanations.risk_explanation(['Salmonella', 'Listeria'], max_output_tokens=2000)

In [29]:
len(exp)

1887

In [30]:
display(Markdown(exp))

Here is information regarding the microorganisms detected in your food:

### Salmonella
Eating food contaminated with Salmonella can lead to salmonellosis, a common type of food poisoning. This infection primarily affects your intestines, causing uncomfortable gastrointestinal symptoms. While most healthy individuals recover, severe cases can lead to dehydration and, if the bacteria spread to the bloodstream, can become life-threatening.

Young children, older adults, and individuals with weakened immune systems are at a much higher risk for severe illness, including more serious infections that can spread beyond the gut.

Symptoms typically begin 6 hours to 6 days after consuming contaminated food. Look out for diarrhea (which may be bloody), fever, and stomach cramps. Nausea and vomiting can also occur. These symptoms usually last for 4 to 7 days.

### Listeria
Consuming food contaminated with Listeria monocytogenes can cause listeriosis, a serious infection. While healthy people might experience mild, flu-like symptoms, listeriosis can lead to severe, invasive illness, including meningitis (inflammation of the brain and spinal cord) or septicemia (blood poisoning), which can be fatal.

Pregnant women, newborns, older adults, and people with weakened immune systems are at significantly higher risk for severe illness. For pregnant women, listeriosis can cause miscarriage, stillbirth, premature delivery, or life-threatening infection in the newborn.

Symptoms can appear anywhere from a few days to several weeks (up to 70 days) after eating contaminated food. For healthy individuals, symptoms might include fever, muscle aches, nausea, or diarrhea. In more severe cases, especially for sensitive populations, symptoms can include headache, stiff neck, confusion, loss of balance, and convulsions, indicating a more serious infection of the brain or bloodstream.

## Testing recipes module
3 levels :
- 'raw'
- 'medium'
- 'high'

In [ ]:
# from interface import recipes

In [ ]:
# raw_beef = recipes.recipe_suggestion(ingredient='beef', cooking='raw', provider='auto', max_output_tokens=5000)
# raw_poultry = recipes.recipe_suggestion(ingredient='poultry', cooking='raw', provider='auto', max_output_tokens=5000)

In [ ]:
# display(Markdown(raw_beef))

### 1. Classic Beef Carpaccio

**Description:** Ultra-thin slices of raw beef tenderloin, drizzled with high-quality olive oil and fresh lemon juice. This delicate and elegant appetizer is often garnished with capers, arugula, and shaved Parmesan.

**Key Ingredients:**
*   Beef tenderloin (center cut)
*   Extra virgin olive oil
*   Fresh lemon juice
*   Capers
*   Arugula
*   Parmesan cheese (optional, for shaving)
*   Sea salt
*   Freshly ground black pepper

**Basic Preparation Steps:**
1.  Wrap the beef tenderloin tightly in plastic wrap and freeze for 30-60 minutes to firm it up for easier slicing.
2.  Using a very sharp knife or a mandoline, slice the beef into paper-thin rounds.
3.  Arrange the beef slices in a single layer on chilled plates, slightly overlapping if necessary.
4.  Drizzle generously with olive oil and fresh lemon juice.
5.  Season with sea salt and black pepper, then scatter capers and arugula over the top.
6.  (Optional) Shave Parmesan cheese over the dish just before serving.

---

### 2. Traditional Steak Tartare

**Description:** Finely hand-chopped raw beef, seasoned with a classic blend of shallots, capers, cornichons, and Dijon mustard. This rich and flavorful dish is traditionally served with a raw egg yolk and toast points.

**Key Ingredients:**
*   Beef tenderloin or sirloin (high quality, very fresh)
*   Shallots
*   Capers
*   Cornichons (gherkins)
*   Dijon mustard
*   Worcestershire sauce
*   Fresh egg yolk
*   Sea salt
*   Freshly ground black pepper

**Basic Preparation Steps:**
1.  Trim the beef of any fat or sinew, then finely hand-chop it into small, uniform pieces. Avoid using a food processor.
2.  In a bowl, combine the chopped beef with finely diced shallots, capers, and cornichons.
3.  Add Dijon mustard, Worcestershire sauce, salt, and pepper. Mix gently to combine all ingredients.
4.  Taste and adjust seasoning as needed. Form the mixture into a patty or mound on a chilled plate.
5.  Create a small indentation on top and carefully place a fresh egg yolk in it.
6.  Serve immediately with crusty bread or toast points.

---

### 3. Korean Yukhoe

**Description:** A vibrant Korean raw beef dish featuring finely julienned beef seasoned with a savory and sweet blend of soy sauce, sesame oil, garlic, and Asian pear. It's often garnished with a raw egg yolk and pine nuts for added richness and texture.

**Key Ingredients:**
*   Beef tenderloin or sirloin (high quality, very fresh)
*   Asian pear
*   Soy sauce
*   Sesame oil
*   Minced garlic
*   Sugar
*   Toasted sesame seeds
*   Green onion (scallion)
*   Fresh egg yolk
*   Pine nuts (optional)

**Basic Preparation Steps:**
1.  Freeze the beef for about 30 minutes to firm it up, then thinly slice and julienne it into fine strips.
2.  Julienne the Asian pear into similar-sized strips.
3.  In a separate bowl, whisk together soy sauce, sesame oil, minced garlic, sugar, and toasted sesame seeds to create the dressing.
4.  Gently toss the julienned beef and pear with the dressing until well coated.
5.  Arrange the mixture on a chilled plate, garnish with finely chopped green onion and pine nuts.
6.  Create an indentation in the center and top with a fresh egg yolk just before serving.

---

### 4. Beef Tiradito with Aji Amarillo Leche de Tigre

**Description:** A Peruvian-inspired dish where thinly sliced raw beef is "cooked" by a vibrant, spicy, and acidic leche de tigre. This zesty marinade, made from aji amarillo, lime juice, and aromatics, infuses the beef with bright, complex flavors.

**Key Ingredients:**
*   Beef tenderloin (high quality, very fresh)
*   Fresh lime juice
*   Aji amarillo paste
*   Red onion
*   Cilantro
*   Garlic
*   Ginger
*   Sea salt
*   Freshly ground black pepper

**Basic Preparation Steps:**
1.  Freeze the beef for 30-60 minutes to firm it, then slice into very thin rounds or strips (thicker than carpaccio, thinner than sashimi).
2.  For the leche de tigre: Blend lime juice, aji amarillo paste, a small piece of red onion, cilantro, garlic, and ginger until smooth. Strain if desired for a smoother sauce.
3.  Arrange the beef slices on a chilled plate in a single layer.
4.  Pour the prepared leche de tigre generously over the beef, ensuring each slice is coated.
5.  Garnish with thinly sliced red onion and fresh cilantro leaves.
6.  Serve immediately, allowing the acid to subtly "cook" the surface of the beef.

---

### 5. Beef Crudo with Chimichurri Verde

**Description:** Delicate slices of raw beef served with a fresh, herbaceous, and tangy Argentinian-style chimichurri sauce. This vibrant appetizer offers a delightful contrast between the tender beef and the bold, aromatic dressing.

**Key Ingredients:**
*   Beef tenderloin or sirloin (high quality, very fresh)
*   Fresh parsley
*   Fresh oregano
*   Garlic
*   Red wine vinegar
*   Extra virgin olive oil
*   Red pepper flakes (optional)
*   Sea salt
*   Freshly ground black pepper

**Basic Preparation Steps:**
1.  Freeze the beef for 30-60 minutes to firm it up, then slice into very thin rounds or strips.
2.  For the chimichurri: Finely chop the fresh parsley, oregano, and garlic. Combine them in a bowl.
3.  Stir in the red wine vinegar, olive oil, red pepper flakes (if using), salt, and pepper. Let the sauce sit for 10-15 minutes for the flavors to meld.
4.  Arrange the beef slices on a chilled plate.
5.  Spoon the prepared chimichurri generously over the beef.
6.  Serve immediately, allowing the fresh flavors to shine.

In [ ]:
# display(Markdown(raw_poultry))

This ingredient is not suitable for raw preparation.

In [ ]:
# medium_pork = recipes.recipe_suggestion(ingredient='pork', cooking='medium', provider='auto', max_output_tokens=5000)

In [ ]:
# display(Markdown(medium_pork))

Here are 5 recipe suggestions for pork, adhering to your specified temperature constraints:

### 1. Sous-Vide Pork Loin with Herbs

**Short description:** This recipe features a tender pork loin cooked precisely in a water bath with aromatic herbs. The controlled low temperature ensures even cooking and exceptional moisture retention, resulting in a succulent and flavorful dish.

**Key ingredients:**
*   Pork loin
*   Fresh rosemary sprigs
*   Fresh thyme sprigs
*   Garlic cloves, smashed
*   Olive oil
*   Salt and black pepper

**Cooking method with explicit temperature range:** Sous-vide at **70-75°C**.

**Basic preparation steps:**
1.  Season the pork loin generously with salt and pepper.
2.  Place the seasoned pork in a vacuum-sealable bag with rosemary, thyme, smashed garlic, and a drizzle of olive oil.
3.  Vacuum seal the bag, ensuring all air is removed.
4.  Submerge the sealed bag in a preheated water bath set to 70-75°C and cook for 2-3 hours, or until tender.
5.  Remove the pork from the bag, slice, and serve immediately.

---

### 2. Poached Pork Belly with Ginger and Scallion

**Short description:** Succulent pork belly is gently poached in an aromatic broth until incredibly tender and melt-in-your-mouth soft. This method extracts excess fat while infusing the pork with delicate flavors, perfect for slicing and serving with a light dressing.

**Key ingredients:**
*   Pork belly, skin on or off
*   Fresh ginger, sliced
*   Green onions (scallions), cut into large pieces
*   Shaoxing wine (or dry sherry)
*   Water or light chicken broth
*   Salt

**Cooking method with explicit temperature range:** Poaching at **90-95°C**.

**Basic preparation steps:**
1.  Place the pork belly in a pot and cover with water. Add ginger, scallions, Shaoxing wine, and a pinch of salt.
2.  Bring the liquid to a gentle simmer, then reduce heat to maintain a poaching temperature of 90-95°C.
3.  Poach the pork belly for 1.5-2 hours, or until very tender when pierced with a fork.
4.  Carefully remove the pork belly from the liquid and let it cool slightly.
5.  Slice the pork belly thinly and serve warm or at room temperature.

---

### 3. Steamed Pork and Cabbage Dumplings

**Short description:** These delicate dumplings feature a savory filling of seasoned ground pork and finely chopped napa cabbage. Gently steamed, the pork filling remains incredibly moist and flavorful, encased in soft, translucent wrappers.

**Key ingredients:**
*   Ground pork
*   Napa cabbage, finely chopped
*   Fresh ginger, grated
*   Soy sauce
*   Sesame oil
*   White pepper
*   Dumpling wrappers (store-bought)

**Cooking method with explicit temperature range:** Steaming at **<100°C**.

**Basic preparation steps:**
1.  In a bowl, combine ground pork, chopped cabbage, grated ginger, soy sauce, sesame oil, and white pepper. Mix well.
2.  Place a small spoonful of filling in the center of each dumpling wrapper.
3.  Moisten the edges of the wrapper with water and fold to seal, creating pleats if desired.
4.  Arrange the dumplings in a steamer basket lined with parchment paper, ensuring they don't touch.
5.  Steam over simmering water (<100°C) for 8-10 minutes, or until the pork filling is cooked through and the wrappers are translucent.

---

### 4. Low-Temperature Braised Pork Shoulder with Apple Cider

**Short description:** This recipe yields incredibly fork-tender pork shoulder, slowly braised in a rich and aromatic apple cider broth. The extended low-temperature cooking breaks down tough fibers, resulting in succulent, shreddable pork perfect for various uses.

**Key ingredients:**
*   Pork shoulder (Boston butt), boneless
*   Apple cider (unsweetened)
*   Onions, sliced
*   Garlic cloves, minced
*   Bay leaves
*   Fresh thyme sprigs
*   Salt and black pepper

**Cooking method with explicit temperature range:** Controlled low-temperature braising at **95-105°C**.

**Basic preparation steps:**
1.  Season the pork shoulder generously with salt and pepper.
2.  Place the pork in a heavy-bottomed pot or Dutch oven. Add sliced onions, minced garlic, bay leaves, and thyme.
3.  Pour in the apple cider, ensuring the liquid comes about halfway up the pork.
4.  Cover the pot tightly and braise in an oven preheated to 95-105°C for 4-6 hours, or until the pork is easily shredded with a fork.
5.  Remove the pork from the pot, shred, and serve with the braising liquid.

---

### 5. Pork and Mushroom Congee

**Short description:** A comforting and nourishing rice porridge, gently simmered with tender slices of pork and earthy shiitake mushrooms. The pork cooks directly in the simmering congee, absorbing the flavors of the broth and becoming incredibly soft.

**Key ingredients:**
*   Short-grain rice
*   Pork loin or shoulder, thinly sliced
*   Dried shiitake mushrooms, rehydrated and sliced
*   Fresh ginger, julienned
*   Chicken broth or water
*   Soy sauce
*   Sesame oil
*   Green onions, chopped (for garnish)

**Cooking method with explicit temperature range:** Simmering at **90-100°C**.

**Basic preparation steps:**
1.  Rinse the rice thoroughly. In a large pot, combine rice and chicken broth (or water).
2.  Bring to a boil, then reduce heat to a gentle simmer (90-100°C), stirring occasionally to prevent sticking.
3.  Add julienned ginger and sliced rehydrated mushrooms to the congee.
4.  Continue to simmer for 1-1.5 hours, or until the rice has broken down and the congee is thick and creamy.
5.  Add the thinly sliced pork to the simmering congee and cook for another 5-10 minutes, or until the pork is tender and cooked through. Season with soy sauce and a drizzle of sesame oil.

In [ ]:
# high_vegetable = recipes.recipe_suggestion(ingredient='vegetable', cooking='high', provider='auto', max_output_tokens=5000)

In [ ]:
# display(Markdown(high_vegetable))

### 1. Roasted Brussels Sprouts with Balsamic Glaze

**Description:** Tender on the inside and crispy on the outside, these Brussels sprouts are caramelized to perfection. A tangy balsamic glaze adds a burst of flavor to this simple side dish.

**Key Ingredients:**
*   Brussels sprouts
*   Olive oil
*   Balsamic vinegar
*   Salt
*   Black pepper

**Cooking Method:** Roasting at 200°C

**Basic Preparation Steps:**
1.  Preheat oven to 200°C.
2.  Trim and halve the Brussels sprouts.
3.  Toss sprouts with olive oil, salt, and black pepper on a baking sheet.
4.  Roast for 20-25 minutes, shaking the pan occasionally, until tender and caramelized.
5.  While sprouts roast, simmer balsamic vinegar in a small saucepan until reduced and slightly thickened.
6.  Drizzle the balsamic glaze over the roasted sprouts before serving.

---

### 2. Crispy Garlic Parmesan Roasted Broccoli

**Description:** Florets of broccoli are tossed with garlic and Parmesan cheese, then roasted until tender-crisp and slightly charred. This quick and healthy side dish is packed with flavor and texture.

**Key Ingredients:**
*   Broccoli florets
*   Olive oil
*   Minced garlic
*   Grated Parmesan cheese
*   Salt
*   Black pepper

**Cooking Method:** Roasting at 220°C

**Basic Preparation Steps:**
1.  Preheat oven to 220°C.
2.  In a large bowl, toss broccoli florets with olive oil, minced garlic, salt, and pepper.
3.  Spread the seasoned broccoli in a single layer on a baking sheet.
4.  Roast for 15-20 minutes, or until tender and slightly crispy with charred edges.
5.  Remove from oven, sprinkle with Parmesan cheese, and return to oven for 2-3 minutes until cheese is melted and lightly golden.

---

### 3. Crispy Deep-Fried Zucchini Fritters

**Description:** Grated zucchini is mixed into a savory batter and deep-fried until golden brown and crispy. These fritters are a delicious way to enjoy zucchini, offering a delightful crunch with every bite.

**Key Ingredients:**
*   Zucchini
*   All-purpose flour
*   Egg
*   Baking powder
*   Salt
*   Black pepper
*   Vegetable oil for frying

**Cooking Method:** Deep Frying at 170°C

**Basic Preparation Steps:**
1.  Grate zucchini and place in a colander; squeeze out as much excess moisture as possible.
2.  In a bowl, combine the squeezed zucchini with flour, egg, baking powder, salt, and pepper to form a thick batter.
3.  Heat vegetable oil in a deep pot or Dutch oven to 170°C.
4.  Carefully drop spoonfuls of the zucchini batter into the hot oil.
5.  Fry for 3-4 minutes per side, or until golden brown and cooked through.
6.  Remove fritters with a slotted spoon and drain on paper towels.

---

### 4. Charred Grilled Asparagus

**Description:** Fresh asparagus spears are quickly grilled over high heat, resulting in tender-crisp stalks with appealing smoky char marks. A simple seasoning highlights the natural sweetness of the vegetable.

**Key Ingredients:**
*   Asparagus spears
*   Olive oil
*   Salt
*   Black pepper

**Cooking Method:** Grilling over direct high heat (grill surface temperature >200°C)

**Basic Preparation Steps:**
1.  Wash asparagus and snap off the woody ends.
2.  Toss the asparagus spears with olive oil, salt, and black pepper.
3.  Preheat a grill to high heat (ensure grill surface temperature is above 200°C).
4.  Place asparagus directly on the hot grill grates.
5.  Grill for 3-5 minutes, turning occasionally, until tender-crisp with visible char marks.

---

### 5. Sautéed Green Beans with Toasted Almonds

**Description:** Fresh green beans are quickly sautéed in a hot pan until vibrant green and slightly tender-crisp. Toasted almonds add a delightful crunch and nutty flavor to this classic side dish.

**Key Ingredients:**
*   Fresh green beans
*   Olive oil
*   Sliced almonds
*   Minced garlic
*   Salt
*   Black pepper

**Cooking Method:** Sautéing in a pan heated to approximately 160°C (pan surface temperature)

**Basic Preparation Steps:**
1.  Trim the ends of the green beans.
2.  Heat olive oil in a large skillet over medium-high heat (aim for a pan surface temperature of about 160°C).
3.  Add sliced almonds to the hot skillet and toast for 1-2 minutes until golden; remove and set aside.
4.  Add green beans to the same skillet and sauté for 5-7 minutes, stirring frequently, until tender-crisp and vibrant green.
5.  Stir in minced garlic during the last minute of cooking.
6.  Season with salt and pepper, then toss with the toasted almonds before serving.

# Testing decision based on bacterial growth

In [1]:

MICROORGANISM = {
    'lm': {
        'usual_name': 'Listeria monocytogenes',
        'initial': -1.4,
        'raw': 4,
        'medium': 4,
        'fried': 4
    },
    'ss': {
        'usual_name': 'Salmonella enterica',
        'initial': -1.4,
        'raw': 1,
        'medium': 1,
        'fried': 1
    },
    'ec': {
        'usual_name': 'Escherichia coli',
        'initial': -3,
        'raw': -2,
        'medium': -2,
        'fried': -2
    },
    'ta': {
        'usual_name': 'Total bacteria (aerobic mesophilic)',
        'initial': 4,
        'raw': 7,
        'medium': 8,
        'fried': 9
    }
}

In [9]:
logC = 10
bacterias = [
    data['usual_name']
    for data in MICROORGANISM.values()
    if logC >= data['raw']
]
print(f'{bacterias=}')

bacterias=['Listeria monocytogenes', 'Salmonella enterica', 'Escherichia coli', 'Total bacteria (aerobic mesophilic)']

# Baseline model training

## Strategy
- First, we want to run all sequences through the primary model (provide [t] and [logCs]) to extract, each time, the parameters of the primary model. Ideally, everything would be assembled into a table where, for each ResponseID or ComBaseID (sequence number), we have as columns: temperature (and/or pH, aW, etc.), and the values of the model parameters for that sequence.
- Next, we pass the table through the secondary model to obtain, for each parameter of the primary model, the parameters of a secondary model as a function of temperature, pH, etc.
- Ultimately, for each parameter of the primary model, we want a secondary model fitted to our training data, which can later be used to predict the primary model parameters as a function of temperature, pH, aW, etc. These will then be used to predict microbial growth over time using a primary model.

So we need to have the _n_ sequences one by one in order to train the _n_ different primary models, where _n_ = `unique(responseID)`

## Imports from Martine notebook (safer-food.ipynb)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

In [2]:
def import_data():
    conditions = pd.read_csv('../raw_data/Conditions.txt', sep='\t')
    experiment_conditions = pd.read_csv('../raw_data/ExperimentConditions.txt', sep='\t')
    experiments = pd.read_csv('../raw_data/Experiments.txt', sep='\t', encoding='latin1')
    logcs = pd.read_csv('../raw_data/LogCs.txt', sep='\t')
    properties = pd.read_csv('../raw_data/Properties.txt', sep='\t')
    response_properties = pd.read_csv('../raw_data/ResponseProperties.txt', sep='\t')
    responses = pd.read_csv('../raw_data/Responses.txt', sep='\t', encoding='latin1')
    source = pd.read_csv('../raw_data/Source.txt', sep='\t')

    return conditions, experiment_conditions, experiments, logcs, properties, response_properties, responses, source

In [3]:
def merge_data(conditions, experiment_conditions, experiments, logcs, properties, response_properties, responses, source):
    # Pivot ExperimentConditions table to have one row per ExperimentID before the merge
    # This table is not needed for the actual project, but will be useful for us
    # in the future...
    # experiment_conditions_pivot = experiment_conditions.pivot_table(index='ExperimentID', columns='ConditionID', values='Value').reset_index()

    # Merge the tables to create a single DataFrame for analysis. Will join data based on the logcs table
    data = responses.merge(experiments, left_on='ExperimentID', right_on='ID',
                           how='left'
                           ).drop(columns=['ID_y']
                                  ).rename(columns={'ID_x': 'ResponseID'})
    # data = data.merge(experiment_conditions_pivot, on='ExperimentID', how='left')
    data = data.merge(response_properties, on='ResponseID', how='left'
                      ).rename(columns={'Value_x': 'ResponseValue',
                                        'Value_y': 'ResponsePropertiesValue'})
    data = data.merge(logcs, on='ResponseID', how='right')

    return data

In [9]:
def clean_data(df, min_time_threshold=5, max_time_threshold=504, min_temp_threshold=0, max_temp_threshold=30):
    # Remove data points where the maximum time exceeds a certain treshold
    df = df[(df['TObs'] >= min_time_threshold) & (df['TObs'] <= max_time_threshold)]

    # Remove data points where the temperature is outside a certain treshold
    df = df[(df['Temperature'] >= min_temp_threshold) & (df['Temperature'] <= max_temp_threshold)]

    # Keep data from specific matrices only
    food_matrices = ['beef', 'poultry', 'produce', 'seafood', 'pork']
    df = df[df['MatrixID'].isin(food_matrices)].reset_index()

    # Fill missing values in the DataFrame based on the provided fill_values
    # dictionary
    fill_values = {
        #'n2': 78.1,         # Must calculate the O2 and CO2 value too...
        'Temperature': 21,
        #'pH':,              # Use mean value from the in_on group
        #'Aw':,              # Use mean value from the in_on group
        #'pressure': 0.101325,
        #'acetic_acid':0,
        #'alta':0,
        #'apple_polyphenol':0,
        #'ascorbic_acid':0,
        #'benzoic_acid':0,
        #'betaine':0,
        #'calcium_propionate':0,
        #'carvacrol':0,
        #'chitosan':0,
        #'cinnamaldehyde':0,
        #'citric_acid':0,
        #'clo2':0,
        #'co2':0.04,         # Must calculate the O2 and N2 value too...
        #'dextrose':0,
        #'diacetic_acid':0,
        #'edta':0,
        #'erythorbate':0,
        #'ethanol':0,
        #'fat':,             # Use mean value from the in_on group or drop
        #'fructose':0,
        #'garlic':0,
        #'glucose':0,
        #'glycerol':0,
        #'green_tea_leaf':0,
        #'green_tea_polyphenol':0,
        #'hcl':0,
        #'irradiated':0,
        #'irradiation':0,
        #'kcl':0,
        #'lactic_acid':0,
        #'lauricidin':0,
        #'malic_acid':0,
        #'moisture':,        # Use mean value from the in_on group
        #'nacl':,            # Use mean value from the in_on group
        #'nitrate':0,
        #'nitrite':0,
        #'o2':21,              # Must calculate the N2 and CO2 value too...
        #'oregano':0,
        #'pomegranate':0,
        #'potassium_lactate':0,
        #'potassium_sorbate':0,
        #'propionic_acid':0,
        #'propylene_oxide':0,
        #'protein':,         # Use mean value from the in_on group or drop
        #'rosemary':0,
        #'sodium_lactate':0,
        #'sorbic_acid':0,
        #'sucrose':0,
        #'sugar':0,
        #'thymol':0
        'PropertyID': 'Other'
    }

    # Impute missing values for 'MethodID' with the most frequent value
    imputer = SimpleImputer(missing_values=np.nan,
                            strategy='most_frequent')
    imputer.fit(df[['MethodID']])
    df['MethodID'] = imputer.transform(df[['MethodID']]).ravel()

    # Drop columns that are not needed for the analysis.
    columns_to_drop = ['Spec_rate', 'RateMethod', 'Logc0', 'CombaseID_x',
                       'heated', 'OrganismSpecification', 'Comment', 'Ph', 'Aw',
                       'Value_x', 'ComBaseID_x', 'ComBaseID_y', 'UserId',
                       'Assumed', 'index', 'ExperimentID', 'LinkId', 'SourceID',
                       'MethodID']

    for column, value in fill_values.items():
        if column in df.columns:
            df[column] = df[column].fillna(value)

    # Drop columns that are not needed for the analysis
    df = df.drop(columns=columns_to_drop, errors='ignore')

    return df

In [10]:
conditions, experiment_conditions, experiments, logcs, properties, response_properties, responses, source = import_data()
raw_data = merge_data(conditions, experiment_conditions, experiments, logcs, properties, response_properties, responses, source)
clean_df = clean_data(raw_data, min_time_threshold=5, max_time_threshold=504, min_temp_threshold=0, max_temp_threshold=30)

In [14]:
raw_data

,ResponseID,ExperimentID,Spec_rate,RateMethod,MethodID,OrganismID,OrganismSpecification,Comment,Logc0,LogcVar,...,Temperature,LinkId,UserId,PropertyID,Value_x,ComBaseID_x,ID,Time,Value_y,ComBaseID_y
0,38694,39472.0,0.01713,NaN,plate_count,ah,Strain(s): CECT-398,NaN,NaN,4.71,...,1.5,A_1,NaN,NaN,NaN,NaN,1,0.00,4.02,A_1
1,38694,39472.0,0.01713,NaN,plate_count,ah,Strain(s): CECT-398,NaN,NaN,4.71,...,1.5,A_1,NaN,NaN,NaN,NaN,2,22.50,3.99,A_1
2,38694,39472.0,0.01713,NaN,plate_count,ah,Strain(s): CECT-398,NaN,NaN,4.71,...,1.5,A_1,NaN,NaN,NaN,NaN,3,97.75,3.94,A_1
3,38694,39472.0,0.01713,NaN,plate_count,ah,Strain(s): CECT-398,NaN,NaN,4.71,...,1.5,A_1,NaN,NaN,NaN,NaN,4,117.50,3.92,A_1
4,38694,39472.0,0.01713,NaN,plate_count,ah,Strain(s): CECT-398,NaN,NaN,4.71,...,1.5,A_1,NaN,NaN,NaN,NaN,5,144.25,3.78,A_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484891,60418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,419495,6.50,5.43,Lm_paneer_40C_T2
484892,60418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,419496,17.00,6.70,Lm_paneer_40C_T2
484893,60418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,419497,21.00,7.51,Lm_paneer_40C_T2
484894,60418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,419498,24.00,7.79,Lm_paneer_40C_T2
484895,60418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,419499,30.00,7.78,Lm_paneer_40C_T2

In [13]:
clean_df

,ResponseID,OrganismID,LogcVar,TObs,MatrixID,In_on,Temperature,PropertyID,ID,Time,Value_y
0,43334,lm,7.00,360.0,beef,ground beef,10.0,Other,2525,0.0,3.39
1,43334,lm,7.00,360.0,beef,ground beef,10.0,Other,2526,24.0,4.99
2,43334,lm,7.00,360.0,beef,ground beef,10.0,Other,2527,31.0,4.33
3,43334,lm,7.00,360.0,beef,ground beef,10.0,Other,2528,48.0,4.77
4,43334,lm,7.00,360.0,beef,ground beef,10.0,Other,2529,55.0,5.71
...,...,...,...,...,...,...,...,...,...,...,...
53247,60240,ss,2.73,7.0,poultry,cucumber,30.0,Other,418101,7.0,3.81
53248,60241,ss,3.13,7.0,poultry,cucumber,30.0,Other,418102,1.0,1.09
53249,60241,ss,3.13,7.0,poultry,cucumber,30.0,Other,418103,3.0,1.82
53250,60241,ss,3.13,7.0,poultry,cucumber,30.0,Other,418104,5.0,2.75
53251,60241,ss,3.13,7.0,poultry,cucumber,30.0,Other,418105,7.0,4.22